development:
  adapter: postgresql
  database: mygradebook_js_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: mygradebook_js_test
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  database: mygradebook_js_production
  pool: 5
  timeout: 5000
